# Generated by Django 4.0.4 on 2022-06-01 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_client'),
        ('productos', '0001_initial'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('nit', models.IntegerField()),
                ('code', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.client')),
            ],
        ),
        migrations.RenameModel(
            old_name='Bills_products',
            new_name='Bill_product',
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
        migrations.AlterField(
            model_name='bill_product',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.bill'),
        ),
    ]
